#!/bin/sh
# $Id: runcase,v 1.3 2001-06-18 08:35:23 ctl Exp $
# =1=
# First sync task: Sync Mr V's changes (L2) and Liisas (L3) into the
# centralized list (L0) output = L4
# The calling order is L3 L2 to get the inserts in facit order
#
echo TASK 1
3dm --merge L0.xml L3.xml L2.xml g4.xml
# check
3dm --diff g4.xml L4.xml

# =2=
# Update the combined human list (l4) to the suggested list (l1) => l5
#
echo TASK 2
3dm --merge L0.xml L4.xml L1.xml g5.xml
# check
3dm --diff g5.xml L5.xml

# =3=
# Presenting the changes between the human list (L4) and the compulist (L6)
# We want to generate an ed script to see what the compu has changed.
#
echo TASK 3
3dm -e --merge L4.xml L6.xml L4.xml > /dev/null
# check the edit script
3dm --diff edit.log editL4L6.xml

# =4=
# Updating the list in Liisa's PDA = send diff between L3 and L7 to L's PDA
#
echo TASK 4
3dm --diff L3.xml L7.xml patch.xml
3dm --patch L3.xml patch.xml g7.xml
# check
3dm --diff L7.xml g7.xml


